# Data Prepration

In [1]:
from prepross import *
import numpy as np
import os
import dataloader
from dataloader import Vocab
pd.options.display.max_rows = 100
from embedding import Doc2VecEmbedding
import pickle
import numpy as np
import time

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/mehrazin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/mehrazin/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
class Parse():
    def __init__(self):
        self.test_mode = True
arg = Parse()

In [3]:
config = Config(arg)

In [4]:
config.exp_dir

'/home/mehrazin/Documents/DAV_project/Repository/Music-Recommendation/Dumped/9'

In [5]:
config.Dataset_dir

'/home/mehrazin/Documents/DAV_project/Repository/Music-Recommendation/Dataset/Test/1k-item/Datasets'

In [6]:
# df = Data_handler(config, pass_col = ['lyrics'])
# df.data = df.get_masked_data(users = df.users[:3], fracs = [0.1,0.2,0.1])
# df.data = create_session(df.data, config)
# df.data = clean_data(df.data, config)
# df.data = cut_sessions(df.data, config)
# config.clean_mode = ['rm_small_sub_session']
# df.data = clean_data(df.data, config)
# df.data

# Model Prepration

In [7]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from dataloader import Music_data, create_data_loader
import torch.nn.functional as F
import Model

In [8]:
embedding, dim = Model.create_embeding(config)
loader = create_data_loader(config, 'train')
itr = iter(loader)
df = Music_data(config, 'train')

In [11]:
i = next(itr)


In [15]:
i[1]

(tensor([[  1,   1,   1,   1],
         [ 39,  39, 164, 164],
         [330, 330, 167, 167],
         [679, 679,   1, 160],
         [114, 114,   0,   1],
         [736, 736,   0,   0],
         [131, 131,   0,   0],
         [  1,  22,   0,   0],
         [  0,   1,   0,   0]]),
 tensor([8, 9, 4, 5]))

In [16]:
u, inpu, out = i

In [19]:
inpu[0]

tensor([[  1,   1,   1,   1],
        [ 39,  39, 164, 164],
        [330, 330, 167, 167],
        [679, 679,   1, 160],
        [114, 114,   0,   1],
        [736, 736,   0,   0],
        [131, 131,   0,   0],
        [  1,  22,   0,   0],
        [  0,   1,   0,   0]])

In [20]:
emb = embedding(inpu[0])

In [22]:
emb.shape

torch.Size([9, 4, 500])